name: AlphaFold base
run-name: Build AlphaFold base container
on:
  workflow_dispatch:

env:
  tool_name: "alphafold"

jobs:
  build_alphafold:
    if: vars.BUILD_CONTAINER == 'true' 
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Get version
        run: |
          cd modules/${tool_name}
          current_commit=$(git rev-parse HEAD)
          git_tag=$(git show-ref --tags | grep ${current_commit} | awk '{print $2}' | sed -e 's|refs/tags/||g')
          echo "container_tag=${git_tag}-base" >> $GITHUB_ENV
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: modules/$tool_name
          file: recipes/docker/${{ tool_name }}-base.Dockerfile
          push: true
          tags: ${{ vars.DOCKERHUB_USERNAME }}/${{ github.actor }}:$container_tag
      - run: echo "This job's status is ${{ job.status }}."

